# the tokio/tracing optional feature needs the tokio_unstable flag
# the reqwest test dependency http3 features needs the reqwest_unstable flag
[build]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "reqwest_unstable"]

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
panic = "abort"

# [unstable]
# build-std = ["core", "alloc", "std", "panic_abort"]

[test]
rustflags = ["--cfg", "tokio_unstable", "--cfg", "reqwest_unstable"]